#pragma once

static const char *arrow_move[] = {
	/* width height num_colors chars_per_pixel */
	"    32    32        3            1",
	/* colors */
	"X c #000000",
	". c #ffffff",
	"  c None",
	/* pixels */
	"                                ",
	"                                ",
	"                                ",
	"         XX                     ",
	"     XXXX..XXXX                 ",
	"     X..X..X..X                 ",
	"     X..X..X..XXX               ",
	"     X..X..X..X..X              ",
	"     X..X..X..X...X             ",
	"   XXX............X             ",
	"  X..X............X             ",
	"  X..X............X             ",
	"  X...............X             ",
	"  X...............X             ",
	"  X...............X             ",
	"  X...............X             ",
	"   X.............X              ",
	"   X.............X              ",
	"    X............X              ",
	"     X..........X               ",
	"     X..........X               ",
	"     XXXXXXXXXXXX               ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"0,0"
};

static const char *arrow_eye[] = {
	/* width height num_colors chars_per_pixel */
	"    32    32        3            1",
	/* colors */
	"X c #000000",
	". c #ffffff",
	"  c None",
	/* pixels */
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"        XXXXXXXXXXXXXXXX        ",
	"     XXX................XXX     ",
	"   XX..........XX..........XX   ",
	"  X...........X..X...........X  ",
	"   XX..........XX..........XX   ",
	"     XXX................XXX     ",
	"        XXXXXXXXXXXXXXXX        ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"0,0"
};
