#pragma once

static const char *arrow_move[] = {
	/* width height num_colors chars_per_pixel */
	"    32    32        3            1",
	/* colors */
	"X c #000000",
	". c #ffffff",
	"  c None",
	/* pixels */
	"                                ",
	"                                ",
	"                                ",
	"         XX                     ",
	"     XXXX..XXXX                 ",
	"     X..X..X..X                 ",
	"     X..X..X..XXX               ",
	"     X..X..X..X..X              ",
	"     X..X..X..X...X             ",
	"   XXX............X             ",
	"  X..X............X             ",
	"  X..X............X             ",
	"  X...............X             ",
	"  X...............X             ",
	"  X...............X             ",
	"  X...............X             ",
	"   X.............X              ",
	"   X.............X              ",
	"    X............X              ",
	"     X..........X               ",
	"     X..........X               ",
	"     XXXXXXXXXXXX               ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"0,0"
};

static const char *arrow_eye[] = {
	/* width height num_colors chars_per_pixel */
	"    32    32        3            1",
	/* colors */
	"X c #000000",
	". c #ffffff",
	"  c None",
	/* pixels */
	"                                ",
	"                                ",
	"                                ",
	"            XXXXXX              ",
	"          X........X            ",
	"        X............X          ",
	"      X................X        ",
	"    X........XXXX........X      ",
	"   X.......XX....XX.......X     ",
	"  X........X......X.......X     ",
	"  X........X......X........X    ",
	"   X.......XX....XX.......X     ",
	"    X........XXXX........X      ",
	"      X................X        ",
	"        X............X          ",
	"          X........X            ",
	"            XXXXXX              ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"0,0"
};

static const char *arrow_zoom[] = {
	/* width height num_colors chars_per_pixel */
	"    32    32        3            1",
	/* colors */
	"X c #000000",
	". c #ffffff",
	"  c None",
	/* pixels */
	"                                ",
	"                                ",
	"                                ",
	"      XXX                       ",
	"    XX...XX                     ",
	"   X.......X                    ",
	"  X..XXXXX..X                   ",
	" X..X.....X..X                  ",
	" X..X..X..X..X                  ",
	"X..X...X...X..X                 ",
	"X..X.XXXXX.X..X                 ",
	"X..X...X...X..X                 ",
	" X..X..X..X..X                  ",
	" X..X.....X..X                  ",
	"  X..XXXXX..X.X                 ",
	"   X.......X...X                ",
	"    XX...XX X...X               ",
	"      XXX    X...X              ",
	"              X...X             ",
	"               X...X            ",
	"                X..X            ",
	"                 XX             ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"0,0"
};
